# Common configuration file across targets

# Enable Module
CONFIG_HYPERPULSE=y
CONFIG_HYPERPULSE_AUTO_LIB_INIT=n

# Logging
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BUFFER_SIZE=10240
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_TIMESTAMP_64BIT=y
CONFIG_LOG_RUNTIME_FILTERING=y
CONFIG_NCS_BOOT_BANNER=n

CONFIG_LED=y
CONFIG_LED_GPIO=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_PM_DEVICE=y

# Disable file system logging
CONFIG_FS_LOG_LEVEL_OFF=y

CONFIG_TFM_LOG_LEVEL_SILENCE=y

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

CONFIG_STATIC_INIT_GNU=y
